Add setup for node-reth (#446)

diff --git a/reth/Dockerfile b/reth/Dockerfile
--- a/reth/Dockerfile
+++ b/reth/Dockerfile
@@ -22,13 +22,30 @@ WORKDIR /app
 RUN apt-get update && apt-get -y upgrade && apt-get install -y git libclang-dev pkg-config curl build-essential
 
 ENV REPO=https://github.com/paradigmxyz/reth.git
-ENV VERSION=v1.3.11
-ENV COMMIT=e0e85aa10b98fa92d32c3e820c7ed2cee0b02931
+ENV VERSION=v1.3.12
+ENV COMMIT=6f8e7258f4733279080e4bd8345ce50538a40d6e
 RUN git clone $REPO --branch $VERSION --single-branch . && \
     git switch -c branch-$VERSION && \
     bash -c '[ "$(git rev-parse HEAD)" = "$COMMIT" ]'
 
 RUN cargo build --bin op-reth --profile maxperf --manifest-path crates/optimism/bin/Cargo.toml
+
+FROM rust:1.85 AS reth-base
+
+WORKDIR /app
+
+RUN apt-get update && apt-get -y upgrade && \
+    apt-get install -y git libclang-dev pkg-config curl build-essential && \
+    rm -rf /var/lib/apt/lists/*
+
+ENV REPO=https://github.com/base/node-reth.git
+ENV VERSION=main
+ENV COMMIT=c23179dc3531a988e483b05d306539cca99f9a5c
+RUN git clone $REPO --branch $VERSION --single-branch . && \
+    git switch -c branch-$VERSION && \
+    bash -c '[ "$(git rev-parse HEAD)" = "$COMMIT" ]' || (echo "Commit hash verification failed" && exit 1)
+
+RUN cargo build --bin base-reth-node --release
 
 FROM ubuntu:22.04
 
@@ -41,6 +58,7 @@ WORKDIR /app
 
 COPY --from=op /app/op-node/bin/op-node ./
 COPY --from=reth /app/target/maxperf/op-reth ./
+COPY --from=reth-base /app/target/release/base-reth-node ./
 COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 COPY ./reth/reth-entrypoint ./execution-entrypoint
 COPY op-node-entrypoint .
